version: "3.9"

services:
  mysql:
    image: mysql:8.4
    container_name: leadergym-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: leader_gym
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_APP_USER}
      MYSQL_PASSWORD: ${MYSQL_APP_PASSWORD}
    ports:
      - "3306:3306"   # opcional; puedes quitarlo en PROD si no quieres acceso externo
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  api:
    build: .
    container_name: leadergym-api
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      SPRING_PROFILES_ACTIVE: prd
      PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/leader_gym?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${MYSQL_APP_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_APP_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"

volumes:
  mysql_data: