spring.application.name=leader-gym

# ===============================
# SERVER
# ===============================
server.port=${PORT:8080}

# ===============================
# DATASOURCE (MySQL)
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/leader_gym}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# LOGGING (opcional, pero Ãºtil)
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
# Sesión 24 horas
server.servlet.session.timeout=24h
server.servlet.session.cookie.max-age=24h
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=lax

# En DEV normalmente false; en PROD true si usás HTTPS
server.servlet.session.cookie.secure=false