spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true


# Sesión 24 horas
server.servlet.session.timeout=24h
server.servlet.session.cookie.max-age=24h
# Permite que la cookie viaje entre dominios (None) y solo por HTTPS (true)
server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true
# Asegura que la cookie no sea accesible por JS (más seguro)
server.servlet.session.cookie.http-only=true


spring.datasource.hikari.maximum-pool-size=4
spring.datasource.hikari.minimum-idle=1
server.tomcat.threads.max=20
logging.level.root=INFO
